### PR TITLE
Add transmission option for elasticsearch

### PR DESCRIPTION
**Pull request by ekouts**
Add an extra transmission option so that xalt data can be sent directly to Elasticsearch with a curl command.

### CODE REVIEW

**Comment by rtmclay** [comment]
Please make XALT_LOGGING_URL a configure option.  Also the TRANSMISSION option needs to be updated in configure.ac.  I also do not like the name "elastic" as the name of the transmission style.  It should be "curl" instead of "elastic"  because that is how the messages are sent.  

You are using curl to transport to something that for you is elasticsearch but it could be anything. Is there something special about how you are transporting with curl that limits it to talking to elasticsearch that I'm missing?

**Comment by rtmclay** [comment]
Also xalt_configuration_report.C will need to be updated.

**Comment by ekouts** [comment]
> You are using curl to transport to something that for you is elasticsearch but it could be anything.

Yes, you are right. Please let me know if I missed anything in the configuration part.

**Comment by rtmclay** [comment]
I started to merge in your feature and I have run into a problem. The problem is that some sites use XALT to track container usage and I don't think that we can assume that every container will have libcurl.so  So I tried to do what I have done with libuuid.so and libcrypto.so and dlopen and dlsym to get access to the functions.  That has worked well for both libraries as the there is only one or two functions required for each library.  

However when I tried to do the same thing with libcurl.so, I ran into the problem with the "routine" curl_easy_setopt(...).  the problem is that this function is really a macro and not a simple one.   It doesn't look like my dlopen/dlsym trick is going to work here.   

So I can see two paths here.  (1) Make this a ifdef section (2) See if there is some way to wrap what you currently have in a separate library and then dlopen/dlsysm a single function that takes arguments like the jsonStr and maybe the XALT_LOGGING_URL.

**Comment by rtmclay** [comment]
I have a solution in the works that is simpler in that it doesn't need either (1) or (2).  I'm working out the details.

**Comment by rtmclay** [comment]
The solution is to copy the system libcurl.so.* files to the XALT installed lib64 directory and make the xalt executables like xalt_run_submission rpath that directory.  This way it will work outside AND inside containers that are setup to use XALT.  All containers already mount the XALT lib64 directory. 

I have created xalt-2.7.20.  Please test this new version when you get a chance.

**Comment by rtmclay** [comment]
I have done some more work on XALT.  The new version 2.9.9 uses the same technique that was first introduced in xalt-2.7.20.  In the new version the transport method using curl has been moved to a separate program, xalt_curl_transmit. 

If you get a chance, please test XALT-2.9.9 to see if it works for you.

**Comment by vkarak** [comment]
Thanks Robert! @victorusu @ekouts can you a have look into that?

**Pull request merged**
